#!/usr/bin/env bash
dir="$HOME/Pictures/Screenshots"
mkdir -p "$dir"
file="$dir/$(date +'%Y-%m-%d_%H-%M-%S').png"

case "$1" in
  full) grim "$file" ;;
  area) grim -g "$(slurp)" "$file" ;;
  window) grim -g "$(swaymsg -t get_tree | jq -r '.. | select(.focused? == true) | .rect | "\(.x),\(.y) \(.width)x\(.height)"')" "$file" ;;
esac

wl-copy < "$file"
notify-send "Screenshot saved" "$file"
